version: '3.8'

services:
  inaai-fe:
    image: inaai-fe:latest
    build:
      context: .
      args:
        VITE_API_BASE_URL: "http://192.168.192.66:4002/api/v1"
    ports:
      - "5000:5000"
    networks:
      - inaai-network
    environment:
      - DATABASE_URL="postgres://fdbckinaai_dev:4fXLDO1l0hlpiSG@192.168.192.205:5432/dwh"
    restart: always

networks:
  inaai-network:
    driver: bridge
